# Generated by Django 5.1.11 on 2025-08-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_auctionlisting_bid_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="description",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Description"
            ),
        ),
    ]
