# Generated by Django 5.1.11 on 2025-08-23 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bidder",
            ),
        ),
    ]
