# Generated by Django 5.1.11 on 2025-08-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bid_bidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="watchers",
                to="auctions.auctionlisting",
            ),
        ),
    ]
