# Generated by Django 5.1.11 on 2025-08-25 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                default="OPEN",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="won_listing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
